name = "ProgressView"
uuid = "001e2b2b-9a5a-4695-8244-d905e27b08dc"
authors = ["Erik Schnetter <schnetter@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.4"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
